### ISSUE TITLE
Warning: Process-local linalg 32-bit only

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1112]
This is a heads-up for potential future problems and a place to track related developments. 

As @mrfh92 has experienced (and [reported](https://github.com/pytorch/pytorch/issues/93275)) while working on his distributed SVD experiment,  PyTorch uses 32-bit blas libraries.  

That is, for the foreseeable future, Heat can perform parallel linear algebra on humongous matrices only as long as the process-local slices don't contain more elements than a 32-bit integer can represent. 

To be discussed:
- implications / warning for the users
- return a meaningful error
- potential alternatives?

**Comment by mrfh92** [comment]
I had a further look into this problem: it seems that actually not the number of elements in the local array is what has to be bounded by the maximum32-bit int, but instead the size of the potential workload has to be bounded by this number. Hence, I guess that routines that require rather much memory (e.g. SVD) will fail earlier than those requiring less memory (e.g. matmul). In particular, printing a warning will be difficult because failure does not only depend on the size of the local arrays alone but also on the operations we want to perform on it. 

So, from my point of view the actions to be taken are: 
* verify that what I wrote above is true (e.g., by experiments) 
* find in the documentation of Blas/LaPack how the workload variable is calculated 
* print warnings in Heat if this workload variable gets bigger than maximum 32-bit int

**Comment by mrfh92** [comment]
There is currently no way to circumvent this issue (see linked PyTorch issue above) and also no possibility to generate a reasonable warning since the actual value of the workload size is not well-documented. 

Therefore closed within #1109
