### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1186]
**Feature functionality**
I propose to update the README description of Heat to:

- (urgent) contain less blurb, more examples/illustrations
- (optional) point to a handful of high-priority Good First Issues for new users
-  (from closed #612:) hello world example or link to a hello work example, if the examples so far are considered as not sufficient 
- more TBD

**Comment by Sai-Suraj-27** [comment]
@ClaudiaComito mam, I think it would be nice if we remove [Resources](https://github.com/helmholtz-analytics/heat#resources) section and shorten the [Contribution guidelines](https://github.com/helmholtz-analytics/heat#contribution-guidelines) section since there is already a `contributing.md` file and replace them with more examples and Good First issues.

**Comment by mrfh92** [comment]
Added comment regarding "hello world example" from closed #612 
Stil ongoing work and useful. 

Reviewed within #1109
