### ISSUE TITLE
[Bug]:  `UserWarning: TypedStorage is deprecated.`

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1229]
### What happened?

We have a few `torch.Tensor.storage()` calls across the codebase, most notably in the `communication` module. PyTorch raises the following warning (see below).

Update code wherever needed (call `Tensor.untyped_storage()` instead of `Tensor.storage()`, check for backward compatibility). 

### Error message or erroneous outcome

```shell
UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
```

### Version

1.3.x

### Python version

None

### PyTorch version

None

**Comment by mrfh92** [comment]
Resolved by merging #1230

Note: since this will only become an actual bug when deprecation actually happens in a future PyTorch release, we handeled our adaptations as "feature" instead of "bug", i.e. #1230 has been merged into main (development version) instead of a bug fix version of the current release.
