### ISSUE TITLE
[Bug]: Release v1.3.1 did not generate a zenodo entry

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1308]
### What happened?

Each of our releases should automatically generate a zenodo entry and a DOI. It looks like this didn't work for v1.3.1:

https://zenodo.org/doi/10.5281/zenodo.2531472

@JuanPedroGHM might this be related in some way to the changelog's failure to update? 

### Version

1.3.x

### Python version

None

### PyTorch version

None

**Comment by JuanPedroGHM** [comment]
I did some quick digging, and found some stuff:

- The Heat Zenodo integration is off.
- The the last run failed because there is some formatting issues with citation file. 
- Other repos had similar issues lately, they fixed it by using a citation file validation commit hook:
  - https://github.com/nsidc/usaon-benefit-tool/pull/199
  - https://github.com/zenodo/zenodo/issues/2515
