### ISSUE TITLE
[Bug]: Refactor `DNDarray.get_halo`

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1570]
### What happened?

Notes from the PR meeting this morning (subject to change, feel free to edit):
- [ ] function should return prev and next halos as torch tensors, not write them into properties of the input
- [ ] remove `halo` properties of DNDarray?
- [ ] decide on processes synchronization [background: when implementing `unfold` we have decided to use non-blocking sends and receives and a subsequent synchronization. Maybe there is a more efficient realization of communicating halos...]

See #1419 

### Version

main (development branch)

### Python version

None

### PyTorch version

None

**Comment by FOsterfeld** [comment]
I also observed the following behavior of` get_halo()`:

If we call `get_halo()`, then do a resplit_ that invalidates the saved halo and then call `get_halo(0)`, the saved halo from the first call does not get reset and thus `array_with_halos()` would throw an error due to invalid shapes. In general, calling `get_calo(0)` does not remove the saved halos as one might expect and this might lead to errors later on.

**Comment by mrfh92** [comment]
an idea brought up by @JuanPedroGHM: use `Sendrecv`
