### ISSUE TITLE
Allow Fortran-style memory layout

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#372]
**Feature functionality**
Allow that tensors have Fortran-style, i.e. column-first, data layout. PyTorch supports this feature now directly via a passable parameter. This issue requires to work through factory functions, the creation of layout conversion calls as well as an investigation if and where auto-conversion between C- and Fortran-style layout needs to happen.

**Comment by ClaudiaComito** [comment]
@Markus-Goetz 
we're talking about introducing a kwarg order='C' (or 'F')  like for numpy arrays, correct?
 
I'm not quite sure which torch parameter you're referring to, with PyTorch 1.2 there's a new tensor attribute torch.layout, but  if I understand it correctly, it can be used to define a dense vs. a sparse tensor.

**Comment by ClaudiaComito** [comment]
@Markus-Goetz 

Just checking if we are on the same page. For ndarrays, order='C' (default, rows first), or order='F' (columns first). So what we're talking about is to allow for a ht.tensor attribute `order` so that the memory layout of the tensor can be specified (or modified). E.g.:

`a = ht.zeros((3,4,5), order='F')`

would create a tensor with Fortran-style memory layout. We would then have a `strides` method to check the layout.

(Numpy details [here](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#internal-memory-layout-of-an-ndarray))

I'm not sure about what PyTorch parameter you're referring to. With PyTorch 1.2.0 we can specify the memory layout (they call it `memory_format`) when creating a torch tensor, but this is with 4d tensors in NCHW order - <batch, channels, width, height> - in mind. It's not what we want.
https://github.com/pytorch/pytorch/issues/19092

Then there's the torch.Tensor attribute `layout`, the only two options are `torch.strided` (default) or `torch.spare_coo`, so this isn't what we need either.
https://pytorch.org/docs/stable/tensor_attributes.html#torch-layout

So far, within torch the only way I've found of having  column-major data layout is:

```
t = torch.randn(3, 5)
t = t.t().contiguous().t()
```

or

`t.set_(t.storage(), t.storage_offset(), t.size(), tuple(reversed(t.stride())))`

(from [here](https://discuss.pytorch.org/t/pytorch-tensor-to-fortran-style-ordering/17670/4))
