### ISSUE TITLE
DNDarray extension allowing to not have all data in RAM

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#641]
**Feature functionality**
Allow for DNDarrays to not have all necessary data directly in RAM. Instead, the data is only partially loaded from disk and swapped in and out adaptively.

**Additional context**
This feature is (almost) identical to what NumPy's `memmap` provides.

**Comment by mrfh92** [comment]
This is certainly of interest, in general; however, there have been no attempts to address this issue so far and, moreover, this functionality would require heavy modification of Heats core datastructure and is not of high priority because one of Heats selling points is memory-distributed computing to overcome memory problems. 

Thus, closed within #1109
