### ISSUE TITLE
resplit after indexing

### ISSUE THREAD

**Issue by mtar** [helmholtz-analytics/heat#769]
**Description**
A clear and concise description of the bug and the associated functionality.
Resplitting after indexing a distributed array may return an array with bad data.

**To Reproduce**
1. Which module/class/function is affected?
DNDarray.__getitem__ + DNDarray.resplit/DNDarray.resplit_/manipulations.resplit
2. What are the circumstances under which the bug appears?
Distributed array; index along axis != split, start index > 0; resplitting to None
3. What is the exact error message / erroneous behavior?
Wrong data in the array.

**Expected behavior**
Same data output after resplitting

**Illustrative**
If applicable, add screenshots or minimal examples to help explain your problem.
```
t1 = ht.array([[1, 2], [3, 4.]], split=0)
t1_sub = t1[:,1]
t1_sub.resplit_(axis=None)
```
DNDarray([5.8775e-39, 5.9234e-39], dtype=ht.float32, device=cpu:0, split=None)

**Version Info**
 Which version are you using?
master fb1e4fd099664f77671d056b5fcd2293813c88f9

**Additional comments**
Any other comments here.

**Comment by coquelin77** [comment]
So this bug comes from the nature of python's referencing to data objects. When an object is sliced, it creates a reference to the original object. While this is typically fine, it can cause issues with redistribution to do alltoallv operations (things like resplit) because there is no way of knowing the original memory positions of the data elements in the slice. 

At this point in time, the simplest option is to copy the sliced data (`.copy()`) before doing the `resplit_`.

**Comment by coquelin77** [comment]
okay. i think that i have found a way to fix this. but more testing is required to determine if it breaks other things
