### ISSUE TITLE
0-dimensional tensor not composable

### ISSUE THREAD

**Issue by fschlimb** [helmholtz-analytics/heat#770]
A simple program like
```
import heat as ht
a = ht.ones(128, split=0)
a = a + a[0]
```
gives an error message. Re-balancing the 0-dimensional tensor `a[0]` as suggested in a warning is neither useful nor possible (same error).

I know I can cast it to a scalar, but that's not very convenient if I want to implement a generic feature.

What is needed to make the above work?

**Comment by coquelin77** [comment]
it would be possible to change the behavior of getitem to distribute the single item to all processes. typically, when the shape is reduced to a single value along a dimension the split dimension is reduced by one. perhaps in the case that it is reduced to a single value the value could be distributed to split=None. what do you think @ClaudiaComito ?

**Comment by fschlimb** [comment]
@ClaudiaComito Would it be possible to do the data-replication for 0d-tensors on-demand/lazily?

**Comment by ClaudiaComito** [comment]
@fschlimb I've been racking my brain about this (@Markus-Goetz this is what I wanted to chat about this morning). It is very inconvenient to broadcast the data back and forth every time we slice an element. But operations on `DNDarrays` with `split=None` expect to have the data replicated on each process.

We could add a `DNDarray` property indicating which process contains the data, and the first operation on that element would trigger the broadcast. I guess that's what you mean by "lazily"?

So , something like: 
```
>>> a[0].split
None
>>> a[0].lazy
0
```
(no data on ranks > 0)

or 
```
>>> a[0].split
None
>>> a[0].lazy
None
```
after the first operation has triggered the Bcast.

Thoughts? @coquelin77 @Markus-Goetz , also @ben-bou

**Comment by ben-bou** [comment]
I don't understand how delaying the Bcast ("replication") until the first evaluation would be advantageous. I think this would only be the case if there is no replication to all processes happening but rather the empty processes can "request" the data whenever they need it. How would this be implemented, would the root process have to spawn a "listener" to answer the requests? How can the root process guarantee that the data has not been changed locally?

Alternatively, and I guess this is what is meant here, this case could be seen as an extremely unbalanced dndarrray, and then be redistributed when needed (most notably in the `__setitem__` and `__binary_op__`). I've done some very rudimentary work on such a redistribution, but couldn't figure out how to do it in the case that the split-axis doesn't exist anymore (Apart from simple replication, see above). This is then related to the discussion around @754, where we found that forcing to keep the split-axis is not feasible and decided for the "eager" replication. 

The encountered problems could probably be circumvented by introducing the `lazy` attribute. However, I would propose to make this `non-distributed dndarray` a subclass of DNDarray (or possibly even torch.Tensor), because

1. it is not a feasible dndarray, e.g. the concepts of `lshapes` and `larrays` on the empty processes just don't make sense (we had this in the discussion around @754), but rather just a `torch.Tensor` with the additional attribute of the `owner_rank`. Therefore it supports every `torch.Tensor` operation by prefacing it with `if self.rank == owner_rank` and every `DNDarray` operation by additionally using `comm = MPI_SELF` and `split = None`. 
2. it behaves differently, e.g. 
    - a `redistribute` is essentially a `scatter`
    - in the `__setitem__` the `values` need to be `gather` -ed
    - a binary operation with two of them does not require both to be distributed or replicated but just moved to the same rank
    - an operation with an unsplit DNdarray can result in a `non-distributed dndarray`, but an operation with a split DNDarray should always result in a DNDarray (i.e. trigger a replication).

**Comment by fschlimb** [comment]
@ben-bou Yes, the replication might not be needed. It's a common case when developers use explicit loops and explicit array indexing. 

Imagine a loop like this:
```
def pairwise_distance(X):
    M = X.shape[0]
    N = X.shape[1]
    D = np.empty((M, M), dtype=np.float64, split=0)
    for i in range(M):
        for j in range(M):
            d = 0.0
            for k in range(N):
                tmp = X[i, k] - X[j, k]
                d = d + tmp * tmp
            D[i, j] = sqrt(d)
    return D
```
Any trivial split will require that over time all data points exist on all ranks. At a certain point in time a full replication of all concurrently used 0d arrays is not desired, though.

Of course I do not expect HeAT to perform well on this. I am trying to experiment with an optimizer to address such issues.

Conceptually, there is no need to have a "listener" since every use of a DNDarray is 'collective', so in theory the owner and the consumer both know that the data is needed by the consumer.

**Comment by ClaudiaComito** [comment]
Thanks, I also understand your problem better now.

> 
> Can you suggest a good way to determine the 'home' of the value in a 0d tensor (if not replicated, e.g. on main branch)?
> 

`a[0].create_lshape_map()`  will return a torch tensor of shape `(MPI_WORLD.size, a[0].ndim)` with the local shapes on each rank.  Note that you'll get inconsistent lshapes when the local tensors are empty on the main branch. But for your purpose it should be fine.
