### ISSUE TITLE
Implement eigendecomposition of a DNDarray

### ISSUE THREAD

**Issue by lenablind** [helmholtz-analytics/heat#805]
**Related**
For instance useful for the implementation of DMD (Dynamic Mode Decomposition)

**Feature functionality**
Computation of the eigenvalues and right eigenvectors of a DNDarray
(cf. [numpy.linalg.eig](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html))

**Comment by mrfh92** [comment]
Has not been addressed so far. Furthermore, in this generality --analogue of `np.linalg.eig` (general square matrix) instead of `np.linalg.eigh` (symmetric matrices only)-- this is out of reach at the moment. Moreover, DMD needs to apply `eig` to a rather small (and thus most likely non-split) matrix. 

Therefore, closed within #1109
