### ISSUE TITLE
ht.allclose should factor in the dtype of the inputs when determining the limits

### ISSUE THREAD

**Issue by coquelin77** [helmholtz-analytics/heat#889]
**Feature functionality**
see title

**Motivation**
When using ht.allclose with float32, we expect to have lower precision. But the current limits on `ht.allclose` are derived from numpy (https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) which uses 64 bit numbers as default.

**Comment by NamanKothari5** [comment]
Hi, I m Naman Kothari a sophomore in Information Technology. I wish to work on this issue can you help me out in getting started

**Comment by ClaudiaComito** [comment]
This is still open.

**Comment by ClaudiaComito** [comment]
We won't address this issue. The background is this: `atol` and `rtol` would have to be set manually for many operations anyway, the numpy defaults aren't particularly related to 64-bit precision (otherwise they would be much lower), and the numpy defaults are identicaly to the torch defaults. 

`ht.allclose` will stick to the numpy defaults, deviations will have to be addressed in single test functions like we have been doing so far.

Thanks @Sai-Suraj-27 for looking into this.
