### ISSUE TITLE
Support `savez`/`savez_compressed` and loading NpzFiles

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#950]
Any chance for supporting `savez`/`savez_compressed` and loading NpzFiles?

_Originally posted by @fschlimb in https://github.com/helmholtz-analytics/heat/issues/101#issuecomment-843967591_

References:
- https://numpy.org/doc/stable/reference/generated/numpy.savez.html
- https://numpy.org/doc/stable/reference/generated/numpy.savez_compressed.html

**Comment by Dhruv454000** [comment]
@ClaudiaComito I would like to work on this one.

**Comment by mrfh92** [comment]
Since `.npz`-format is not an HPC-typical format, it does not make sense from my point of view, to save `DNDarray`'s that really need distribution in this format. On the other hand, for `DNDarrays`'s that are sufficiently small to admit conversion to a non-distributed numpy-array, its easy to use this conversion and to save as `.npz` afterwards. 

Therefore, closed within #1109
